tests/main/interfaces-snap-refresh-observe: override Python's IO encoding guess
Python will try to guess the IO encoding based on the terminal, but apparently
not all terminals support UTF-8, thus causing errors like this:

$ PYTHONIOENCODING="ascii" api-client --socket /run/snapd-snap.socket /v2/snaps
Traceback (most recent call last):
  File "/snap/api-client/x1/bin/api-client.py", line 40, in <module>
    sys.exit(main(sys.argv))
  File "/snap/api-client/x1/bin/api-client.py", line 36, in main
    print(body.decode('UTF-8'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 3183: ordinal not in range(128)

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>