cmd/libsnap-confine-private: fix unused variable in unit tests
libsnap-confine-private/locking-test.c: In function ‘test_sc_snap_is_inhibited__missing_file’:
libsnap-confine-private/locking-test.c:169:17: error: unused variable ‘d’ [-Werror=unused-variable]
  169 |     const char *d = sc_test_use_fake_inhibit_dir();
      |                 ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2979: libsnap-confine-private/libsnap_confine_private_unit_tests-locking-test.o] Error 1

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>