tests/nested/core20/basic: wait for system to finish seeding
SSH will become available before the system is done seeding, so we need to wait
for that before trying to install snaps. Example failure:

2020-06-23 15:47:36 Error executing google-nested:ubuntu-20.04-64:tests/nested/core20/basic (jun231820-424078) :
-----
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/nested.sh
++ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/systemd.sh
++ WORK_DIR=/tmp/work-dir
++ NESTED_VM=nested-vm
++ SSH_PORT=8022
++ MON_PORT=8888
+ echo 'Ensure '\''snap install'\'' works'
Ensure 'snap install' works
+ execute_remote 'sudo snap install test-snapd-sh'
+ sshpass -p ubuntu ssh -p 8022 -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user1@localhost 'sudo snap install test-snapd-sh'
Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of known hosts.
error: too early for operation, device not yet seeded or device model not acknowledged
+ true
+ echo 'Ensure '\''snap list'\'' works and test-snapd-sh snap is installed'
Ensure 'snap list' works and test-snapd-sh snap is installed
+ MATCH test-snapd-sh
+ execute_remote 'snap list'
+ sshpass -p ubuntu ssh -p 8022 -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user1@localhost 'snap list'
Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of known hosts.
grep error: pattern not found, got:
Name   Version                  Rev  Tracking  Publisher  Notes
snapd  2.45.1+git1525.g35f56da  x1   -         -          snapd
-----

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>