Create file before write it to avoid issue on the python client creating file
The idea of the test is to write in a file, and as it fails sporadically
on the tests execution the idea of this fix is to pre-create the file
and then check the snap client is able to write on it.

The error which is fixed is:
+ su -l -c 'XDG_RUNTIME_DIR="/run/user/12345"
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/12345/bus"
test-snapd-portal-client save-file from-sandbox' test
Traceback (most recent call last):
  File "/snap/test-snapd-portal-client/2/bin/client.py", line 147, in
<module>
    sys.exit(main(sys.argv))
  File "/snap/test-snapd-portal-client/2/bin/client.py", line 143, in
main
    return client.run(argv[1:])
  File "/snap/test-snapd-portal-client/2/bin/client.py", line 40, in run
    return command(*args)
  File "/snap/test-snapd-portal-client/2/bin/client.py", line 73, in
cmd_save_file
    with open(unquote(parsed.path), "w") as fp:
OSError: [Errno 38] Function not implemented:
'/run/user/12345/doc/d26038d5/file-to-write.txt'