Add fedora to distro_clean_package_cache function
We need this to update the packages from the spread-images project.

In this project there is a task which we use to install/update the
packages for the images, but is it failing for fedora currently.

error:

+ case "$SPREAD_SYSTEM" in
+ quiet dnf -y --refresh install curl dbus-x11 expect git golang jq
iptables-services man mock net-tools redhat-lsb-core rpm-build xdg-user-
dirs
+ rm -rf snapd-master
+ distro_clean_package_cache
+ case "$SPREAD_SYSTEM" in
+ echo 'ERROR: Unsupported distribution fedora-28-64'
ERROR: Unsupported distribution fedora-28-64
+ exit 1