tests: re-execute the failed tests when "Run failed" label is set in the PR  (#11627)
* Update the workflow to save failed tests

* Re run failed tests

This change is done to save the failed tests for a run and execute those
tests when the labed "Run failed" is set in the PR.

The idea of this is to speed up the re-executions

* Update tests dir and indentation

* Improvement in the actions workflow

* Add missing dir

* Fix TEST_RESULTS_DIR creation

* Simplify the actions workflow to run just once the spread tests

* Create the TEST_RESULTS_DIR

* Adding extra info to failed tests check

* Fix to support complex results like the following

2022-04-06 10:35:36 Failed tasks: 3
    - google:arch-linux-64:tests/main/snap-quota
    - google:ubuntu-14.04-64:tests/main/interfaces-many-snap-provided
    - google:ubuntu-21.10-64:tests/unit/go
2022-04-06 10:35:36 Failed task prepare: 1
    - google:ubuntu-14.04-64:tests/main/interfaces-many-core-provided
2022-04-06 10:35:36 Failed task restore: 1
    - google:arch-linux-64:tests/main/snap-quota
error: unsuccessful run

* Minor improvementes based on review comments

* Fix FAILED_TESTS_FILE var name

* Remove " from spread execution line