tests: install ubuntu image snap to build uc18 and uc2* (#12891)
* Install ubuntu image snap to build uc18 and uc2*

This is needed because currently ubuntu-image is failing to build the
ubuntu core image with the following error:

runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc0204963b0 stack=[0xc020496000, 0xc040496000]
fatal error: stack overflow

* Use the ubuntu-image snap