Moving ubuntu-image to candidate to fix uc16 tests
Snapd tests are failing to create a new core image using ubuntu-image
snap from edge channel (rev 275)

This is the error that we see in the logs. The same code works well when
we use ubuntu-image from candidate channel (rev 253)

BUNTU_IMAGE=/snap/bin/ubuntu-image
/snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model
--channel edge --snap
/home/image/core_16-2.55.2+git3709.84f473c15_amd64.snap --output-dir
/home/image
WARNING: proceeding to download snaps ignoring validations, this default
will change in the future. For now use --validation=enforce for
validations to be taken into account, pass instead --validation=ignore
to preserve current behavior going forward
Fetching pc-kernel
Fetching pc
WARNING: "core" installed from local snaps disconnected from a store
cannot be refreshed subsequently!
Copying "/home/image/core_16-2.55.2+git3709.84f473c15_amd64.snap" (core)
WARNING: volumes:pc:structure:2:filesystem_label used for defining
partition roles; use role instead
Error: Error running mkfs with content:
-----
mkfs.ext4: invalid option -- 'd'
Usage: mkfs.ext4 [-c|-l filename] [-b block-size] [-C cluster-size]
 [-i bytes-per-inode] [-I inode-size] [-J journal-options]
 [-G flex-group-size] [-N number-of-inodes]
 [-m reserved-blocks-percentage] [-o creator-os]
 [-g blocks-per-group] [-L volume-label] [-M last-mounted-directory]
 [-O feature[,...]] [-r fs-revision] [-E extended-option[,...]]
[-t fs-type] [-T usage-type ] [-U UUID] [-jnqvDFKSV] device
[blocks-count]