skip itnerfaces-udisks on ubuntu-20.04-64 due to timing issue
The idea is to enable it again once the error is properly fixed.

The test fails due to a timing issue (with a sleep before the mount the
error is not reproduced anymore).

error: https://travis-ci.org/snapcore/snapd/jobs/645851946#L12371