Make sure the persistent-journal-namespace test restores without error (#12167)
This is needed because the test could fail to install
test-snapd-journal-quota and then the following error happens:

2022-09-16 15:09:54 Error restoring
external:ubuntu-core-20-64:tests/core/persistent-journal-namespace
(external:ubuntu-core-20-64) :
-----
+ snap stop test-snapd-journal-quota.logger
error: snap "test-snapd-journal-quota" has no service "logger"