Force delete of files on restore
This change is to avoid this kind of errors on the restore to make sure
it does not fail even when the file to delete does not exist

2017-11-21 12:16:23 Error restoring external:ubuntu-
core-16-64:tests/main/snapctl-from-snap :
-----
+ rm snapctl-from-snap_1.0_all.snap
rm: cannot remove 'snapctl-from-snap_1.0_all.snap': No such file or
directory
-----
.
2017-11-21 12:16:23 Restoring external:ubuntu-core-16-64:tests/main/...
2017-11-21 12:16:26 Restoring project on external:ubuntu-core-16-64...
2017-11-21 12:16:33 Discarding external:ubuntu-core-16-64...
2017-11-21 12:16:33 Successful tasks: 140
2017-11-21 12:16:33 Aborted tasks: 19
2017-11-21 12:16:33 Failed task prepare: 1
    - external:ubuntu-core-16-64:tests/main/snapctl-from-snap
2017-11-21 12:16:33 Failed task restore: 1
    - external:ubuntu-core-16-64:tests/main/snapctl-from-snap
error: unsuccessful run