tests: do not run mem-cgroup-disabled on external backends
External backends fail with:
```
2022-04-11 15:42:24 Error executing external:ubuntu-core-22-64:tests/core/mem-cgroup-disabled (external:ubuntu-core-22-64) :
-----
+ not os.query is-pc-amd64
+ case "$SPREAD_REBOOT" in
++ awk '{print $4}'
++ grep memory
+ '[' 1 '!=' 1 ']'
+ /home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snaps-state install-local test-snapd-simple-service
test-snapd-simple-service 1.0 installed
+ snap set system experimental.quota-groups=true
+ snap set-quota grp --memory=100MB test-snapd-simple-service
+ MATCH Slice=snap.grp.slice
+ snap install --dangerous pc-cgroup-disabled.snap
error: cannot perform the following tasks:
- Mount snap "pc" (unset) (cannot replace signed gadget snap with an unasserted one)
-----
.
2022-04-11 15:42:24 Debug output for external:ubuntu-core-22-64:tests/core/mem-cgroup-disabled (external:ubuntu-core-22-64) :
```

because they don't have a sideloaded gadget. So until
https://github.com/snapcore/snapd/pull/11589

is merged this test needs to be skipped on devices that do not
already sideload the gadget.