cmd/libsnap-confine-private: g_spawn_check_exit_status is deprecated since glib 2.69
With https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1967 the
g_spawn_check_exit_status call is flagged as deprecated now. This also broke in
F35 mass rebuild in Rawhide:

make[1]: Leaving directory '/builddir/build/BUILD/snapd-2.51/cmd'
libsnap-confine-private/test-utils.c: In function 'rm_rf_tmp':
libsnap-confine-private/test-utils.c:63:9: error: 'g_spawn_check_exit_status' is deprecated: Use 'g_spawn_check_wait_status' instead [-Werror=deprecated-declarations]
   63 |         g_assert_true(g_spawn_check_exit_status(exit_status, NULL));
      |         ^~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:81,
                 from libsnap-confine-private/test-utils.c:24:
/usr/include/glib-2.0/glib/gspawn.h:280:10: note: declared here
  280 | gboolean g_spawn_check_exit_status (gint      wait_status,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2705: libsnap-confine-private/libsnap_confine_private_unit_tests-test-utils.o] Error 1
make[1]: *** Waiting for unfinished jobs....

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>