Skip validation of invalid strace on arm devices on snap-run test
This test is failing since long time in arm devices with the same error.
A research was done on this issue but could not be fixed as the problem
is realted to strace.

Skip validation of invalid strace on arm devices due to known error
error: signal: segmentation fault