tests: fix compilation error in snap-seccomp-blocks-certain tests
This change is fixing the compilation error we see in ubuntu-arm
editions.

Compile and prepare the test program
+ gcc -static -Wall -Wextra -Werror ./test.c -o
/var/snap/test-snapd-sh/common/test-creat
./test.c:8:20: error: ‘errno_name’ defined but not used
[-Werror=unused-function]
8 | static const char *errno_name(int e)
|                    ^~~~~~~~~~
cc1: all warnings being treated as errors