tests: add extra storage to arch vms in google cloud
This is to avoid issue like:

error: cannot extract "*" to "/home/test/tmp/kernel":
-----
Write on output file failed because No space left on device
FATAL ERROR: writer: failed to write file
/home/test/tmp/kernel/modules/5.4.0-182-generic/kernel/nvidia-535srv/bits/nvidia/nv-kernel.o