daemon: always generate a snap info for broken snaps when listing all
When calling `snap list`, snaps that are broken will appear with a `broken` note
in the notes column like this:

$ snap list
Name               Version   Rev   Tracking  Publisher     Notes
core               16-2.35   5328  stable    canonical✓    core
hello-world_foo              27    stable    canonical✓    broken

However, when calling `snap list --all`, the client would get an error instead:

$ snap list --all
error: cannot list local snaps! cannot find installed snap "hello-world_foo" at revision 27:
       missing file /var/lib/snapd/snap/hello-world_foo/27/meta/snap.yaml

The ensures that we get consistent error case output for the listing of all
snaps.

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>