Remove systemd-journald restart
This is removed beacuse the bug
https://github.com/systemd/systemd/issues/11502 is already closed.

Also de degraded test was failing because of this:

Error: 2021-03-12 11:28:01 Error executing
google:debian-sid-64:tests/main/degraded (mar121119-891844) :
-----
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/systemd.sh
+ wait_for_service multi-user.target
+ local service_name=multi-user.target
+ local state=active
++ seq 300
+ for i in $(seq 300)
+ grep -q ActiveState=active
+ systemctl show -p ActiveState multi-user.target
+ return
+ case "$SPREAD_SYSTEM" in
+ grep 'State: [d]egraded'
+ systemctl status
    State: degraded
+ echo 'systemctl reports the system is in degraded mode'
systemctl reports the system is in degraded mode
+ systemctl --failed
  UNIT                          LOAD   ACTIVE SUB    DESCRIPTION
● systemd-journal-flush.service loaded failed failed Flush Journal to
Persistent Storage