i/apparmor: fix {personal,system}-files profile if path has spaces (#17502)
A personal-files plug with a path with spaces would fail to connect
because the path was not quoted in snap-update-ns profile.

error: cannot perform the following tasks:
- Connect spaces-demo:foo-plug to snapd:personal-files (cannot setup profiles for snap "spaces-demo": cannot load apparmor profiles: exit status 1
apparmor_parser output:
AppArmor parser error for /var/lib/snapd/apparmor/profiles/snap-update-ns.spaces-demo in profile /var/lib/snapd/apparmor/profiles/snap-update-ns.spaces-demo at line 182: syntax error, unexpected TOK_ID, expecting TOK_MODE
)

Signed-off-by: Miguel Pires <miguel.pires@canonical.com>