tests/main/system-usernames-microk8s: disable on centos 7 too
This test fails on centos 7 thusly:

Error: 2021-07-07 14:10:59 Error executing google:centos-7-64:tests/main/system-usernames-microk8s (jul071354-110681) :
-----
+ echo 'Try to install a snap which is not entitled to use the microk8s user'
Try to install a snap which is not entitled to use the microk8s user
++ snap install test-microk8s-username
++ true
+ OUT='error: cannot perform the following tasks:
- Mount snap "test-microk8s-username" (1) (snap "test-microk8s-username" system usernames require a snapd built against libseccomp >= 2.4)'
+ MATCH 'snap "test-microk8s-username" is not allowed to use the system user "snap_microk8s"'
+ echo 'error: cannot perform the following tasks:
- Mount snap "test-microk8s-username" (1) (snap "test-microk8s-username" system usernames require a snapd built against libseccomp >= 2.4)'
grep error: pattern not found, got:
error: cannot perform the following tasks:
- Mount snap "test-microk8s-username" (1) (snap "test-microk8s-username" system usernames require a snapd built against libseccomp >= 2.4)
-----

So we should disable it.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>