Get lxd snap from candidate channel (#11447)
This is because all the tests that use lxd are failing with the
following/similar error

+ VERSION_ID=20.04
+ lxd.lxc launch --quiet ubuntu:20.04 my-ubuntu
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart my-ubuntu
/var/snap/lxd/common/lxd/containers
/var/snap/lxd/common/lxd/logs/my-ubuntu/lxc.conf:
Try `lxc info --show-log local:my-ubuntu` for more info
-----

I'll create another change to revert this to edge.