tests/nested/manual/remodel-offline: wait for kernel refresh change
Wait for the kernel change to be fully done before proceeding,
otherwise we can have a race condition and remodel will fail with
message:

error: cannot do offline remodel: cannot remodel device: snap
"pc-kernel" has "refresh-snap" change in progress