tests: skip snap-quota-services in external devices (#12820)
* Skip snap-quota-services in external devices

As the other quota tests, we need to disable snap-quota-services too for
external devices.

This is the error in the test

+ snap set-quota test-top --memory=400MB test-snapd-stressd
error: cannot create quota group: cannot create quota group "test-top":
cannot
       use memory quota: memory cgroup is disabled on this system

* skip it for real using backends