tests: fix snap run test for debian-sid
The snap-run test started failing on debian-sid because there was
a change to the message emitted when running strace with an
invalid option.

```
+ MATCH 'Can'\''t stat '\''invalid'\'': No such file or directory'
grep error: pattern not found, got:
/usr/bin/strace: Cannot find executable 'invalid'
error: exit status 1
```

Signed-off-by: Miguel Pires <miguel.pires@canonical.com>