tests: handle "snap refresh" returning an empty reply gracefully
When the store has a bad day it will return errors on snap refresh
like:
```
error: cannot refresh "core18": unexpectedly empty response from the server
       (try again later)
```
This causes the tests/regression/lp-1693042 to fail. Instead
"skip" the test and continue when this happens.