cmd/libsnap-confine-private: fix unused variable
libsnap-confine-private/string-utils-test.c: In function ‘test_sc_string_split_null_prefix_and_suffix’:
libsnap-confine-private/string-utils-test.c:806:14: error: unused variable ‘dest’ [-Werror=unused-variable]
  806 |         char dest[10] = {0};
      |              ^~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:3091: libsnap-confine-private/libsnap_confine_private_unit_tests-string-utils-test.o] Error 1

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>