cmd/snap-seccomp: graceful handling of non-multilib host
Some hosts, eg. Amazon Linux 2, may not have multilib support at all, in which
case any attempt to build the multilib syscall-runner will fail. Since Amazon
Linux 2 is only such host that we know of, make sure that we have an explicit
skip in place.

Example test failure on such host:

=== RUN   Test
cannot build multi-lib syscall runner: exit status 1
In file included from /usr/include/features.h:447:0,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:25,
                 from /tmp/check-2039432933516484279/1/seccomp_syscall_runner.c:3:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
           ^~~~~~~~~~~~~~~~
compilation terminated.

----------------------------------------------------------------------
FAIL: main_test.go:769: snapSeccompSuite.TestCompatArchWorks

main_test.go:791:
    s.runBpf(c, t.seccompWhitelist, t.bpfInput, t.expected)
main_test.go:316:
    c.Fatalf("unexpected error for %q (failed to run %q): %s", seccompWhitelist, lastKmsg(), err)
... Error: unexpected error for "read" (failed to run "Showing last 10 lines of dmesg:\n[ 3484.534825] NET: Registered protocol family 24\n[ 3484.583121] NET: Registered protocol family 21\n[ 3484.651176] NET: Registered protocol family 33
\n[ 3484.651792] Key type rxrpc registered\n[ 3484.652292] Key type rxrpc_s registered\n[ 3484.741025] Guest personality initialized and is inactive\n[ 3484.741932] VMCI host device registered (name=vmci, major=10, minor=58)\n[ 3484.742623
] Initialized host personality\n[ 3484.748088] NET: Registered protocol family 40\n"): signal: bad system call

OOPS: 12 passed, 1 FAILED

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>