travis: use Go 1.11 on OSX
Otherwise golang.org/x/sys/unix breaks with:

../../../golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:687:22: undefined: SYS_CLOCK_GETTIME

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>