Move fedora 27 to manual
Most of the builds are failing in travis because of this error which
could be caused by high load due to fedora 28 which has been released.
quiet dnf -y install /home/gopath/snap-
confine-1337.2.32.6-0.fc27.x86_64.rpm ....
quiet: exit status 1. Output follows:
Error: Failed to synchronize cache for repo 'updates'
quiet: end of output.