DT-1021: discard namespace and retry if updateSnapNamespace fails
Recently, there was a change in the layout of the Steam snap:
some binds were replaced by symlinks. These changes are
currently in the --edge stream, while the --beta stream still
has the binds.

Unfortunately, trying to update from the beta version to the
edge one fails with these errors:

    raster ~$ sudo snap refresh --edge steam
    error: cannot perform the following tasks:
    - Configurar los perfiles de seguridad del snap "steam" (112) (cannot update mount namespace of snap "steam": cannot update preserved namespace of snap "steam": cannot update snap namespace: cannot create symlink in "/usr/lib/i386-linux-gnu/libvulkan_intel.so": existing file in the way)

    raster ~$ sudo snap refresh --edge steam
    error: cannot perform the following tasks:
    - Configurar los perfiles de seguridad del snap "steam" (112) (cannot update mount namespace of snap "steam": cannot update preserved namespace of snap "steam":

    change.go:471: cannot remove mount point, got EBUSY: "/snap/steam/83"
    cannot update snap namespace: cannot create symlink in "/usr/lib/i386-linux-gnu/libvulkan_intel.so": existing file in the way

    raster ~$ sudo snap refresh --edge steam
    error: cannot perform the following tasks:
    - Configurar los perfiles de seguridad del snap "steam" (112) (cannot update mount namespace of snap "steam": cannot update preserved namespace of snap "steam":

    change.go:471: cannot remove mount point, got EBUSY: "/snap/steam/83"
    cannot update snap namespace: cannot create symlink in "/usr/lib/i386-linux-gnu/libvulkan_intel.so": existing file in the way

Manually executing

    "/snap/snapd/current/usr/lib/snapd/snap-discard-ns steam"

fixes the problem and allows to successfully update the snap.

This patch automagically executes the command if the update
fails while updating the snap's namespace, and then retries
the operation. With it, the steam update work flawlessly.

Fix https://github.com/canonical/steam-snap/issues/111