snap: when running `snap repair` without arguments, show hint
When running `snap repair` without argument we show nothing right
now. This is not very useful. This PR changes the code so that
we show a hint like:
```
$ ./snap repair
error: no `<repair-id>` given, did you mean 'snap repairs' to list all repairs?
```