squashfs: reduce the memory consumed by unsquashfs to uncompress a single file
On low-end platforms such as RPi Zero 2W, unsquashfs can fail trying to
unsquash a single file with the following error:

stateengine.go:161: state ensure error: devicemgr: cannot seed: cannot run unsquashfs:
- - - - -
Total memory requested is more than 75% of physical memory.
Unsquashfs uses memory to cache data from disk to optimise performance.
It is pointless to ask it to use more than this amount of memory, as this
causes thrashing and it is thus self-defeating.
FATAL ERROR: Requested memory size too large

This commit limits both the data and fragment queue sizes used by
unsquashfs in order to limit the memory consumption to a minimum.

Signed-off-by: Nicolas Harnois <nicolas.harnois@canonical.com>