vendor: pin golang.org/x/sys/unix to a revision before SYS_CLOCK_GETTIME on OSX
Otherwise it breaks:
```
 ../../../golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:687:22: undefined: SYS_CLOCK_GETTIME
```

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>