cmd/libsnap-confine-private: fix strncpy bounds check
The size argument to strncpy is the destination size. The source string
size has already been verified to be shorter than the required buffer
lengt and we are copying all the remaining input.

libsnap-confine-private/snap.c: In function ‘sc_snap_component_validate’:
libsnap-confine-private/snap.c:311:5: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-truncation]
  311 |     strncpy(component_name, pos + 1, component_name_len);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libsnap-confine-private/snap.c:300:33: note: length computed here
  300 |     size_t component_name_len = strlen(pos + 1);
      |                                 ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2797: libsnap-confine-private/a-snap.o] Error 1
m

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>