cmd: compile snap gdbserver shim correctly
When building with ./configure --enable-silent-rules automake complains
that a SOURCES variable has multiple definitions:

    Makefile.am:497: warning: snap_gdb_shim_snap_gdb_shim_SOURCES multiply defined in condition TRUE ...
    Makefile.am:486: ... 'snap_gdb_shim_snap_gdb_shim_SOURCES' previously defined here

Indeed the gdb shim and gdbserver shim were defined incorrectly. It
seems we have not compiled or tested this code for real before. Whoops.

Ref: https://listed.zygoon.pl/17493/signal-to-noise-ratio-in-build-systems
Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>