Remove old ubuntu-core-transition tests (#11728)
These old tests are failing on nightly run since the new shared-memory
interface was added.

The idea is to remove them as those are very old and shouldn't represent
a usefull scenario currently

+ snap download --edge ubuntu-core
Fetching snap "ubuntu-core"
Fetching assertions for "ubuntu-core"
Install the snap with:
   snap ack ubuntu-core_1797.assert
   snap install ubuntu-core_1797.snap
+ snap ack ./ubuntu-core_1797.assert
+ snap install ./ubuntu-core_1797.snap
error: cannot perform the following tasks:
- Mount snap "ubuntu-core" (1797) (installation not allowed by
"shared-memory" slot rule of interface "shared-memory")