Change how dir is umounted on desktop-portal.sh
This is to avoid error caused for dir not umounted properly

error: https://paste.ubuntu.com/p/VFGvkXN6Wk/