tests/main/snap-info: use yaml.safe_load rather than yaml.load
Update the test script to work correctly with latest releases of PyYAML, which
now require the Loader to be passed for non-safe load() functions, like so:

+ python3 check.py
Traceback (most recent call last):
  File "check.py", line 70, in <module>
    res = list(yaml.load_all(sys.stdin))
TypeError: load_all() missing 1 required positional argument: 'Loader'

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>