add if because debian 12 fails
2026-01-29 21:34:37 Error executing
openstack:debian-12-64:tests/main/debug-execution (jan292130-206473) :
-----
+ snap debug execution snap
+ SNAP_REEXEC=0
+ snap debug execution snap
error: unknown command "execution", see 'snap help debug'.
-----