packaging/fedora: attempt deal with a broken FIPS Go toolchain on RHELs
Explicitly adding no_openssl tag apparently breaks the build with recent
versions of the Go toolchain (observed with 1.22) like so:

crypto/tls
/usr/lib/golang/src/crypto/tls/handshake_client_tls13.go:44:20: undefined: supportsHKDF

However, simply building code without no_openssl where relevant causes runtime
segfaults:

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x66a130, 0xc0000a36f8)
    /usr/lib/golang/src/runtime/cgocall.go:157 +0x5c fp=0xc0000a36d0 sp=0xc0000a3698 pc=0x405c5c
vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
    _cgo_gotypes.go:677 +0x49 fp=0xc0000a36f8 sp=0xc0000a36d0 pc=0x55b549
vendor/github.com/golang-fips/openssl-fips/openssl.init.0()
    /usr/lib/golang/src/vendor/github.com/golang-fips/openssl-fips/openssl/openssl.go:68 +0xdd fp=0xc0000a3730 sp=0xc0000a36f8 pc=0x55c67d
runtime.doInit(0xbcf3a0)

This we selectively apply no-CGO build setup for snap-exec and snapctl. The
snapctl binary does http, and this will rely on crypto from the Go standard
library, which is fine as the communication happens only over a local HTTP
UNIX socket to snapd. However, since snap-update-ns needs C for the early
bootstrap bits, we must pass no_openssl as needed.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>