Adding more space to ubuntu focal to aovid out of space error
This is the error running the test
google:ubuntu-20.04-64:tests/main/snapd-snap:lxd

RuntimeError: Failed to create snap, snap command failed:
stdout:

stderr:
error: cannot pack "/root/prime": mksquashfs call failed:
-----
Write failed because No space left on device
FATAL ERROR:Failed to write to output filesystem
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /root/project/snapd_spread-test.snap, block
size 131072.