travis: disable snap pack on OSX
Relevant build log:

Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects:  35% (26remote: Compressing objects: 100% (74/74), done.
remote: Total 81 (delta 7), reused 27 (delta 4), pack-reused 0
Unpacking objects: 100% (81/81), done.
Tapped 0 formulae (172 files, 244.2KB)
Error: undefined method `present?' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brewfile.rb:12:in `path'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brewfile.rb:26:in `read'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:75:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>