[RFC] many: support `snap install --skip-service-start`
Without this change, if a service requires a connection in order to
run, there is no easy way to debug it as its install will be aborted.

This change adds `--skip-service-start`, which stops the services from
being started on install.

    ~$ snap list xkcd-webserver
    error: no matching snaps installed
    ~$ snap install xkcd-webserver
    xkcd-webserver 16.04-6 from Canonical✓ installed
    ~$ snap services xkcd-webserver
    Service                        Startup  Current  Notes
    xkcd-webserver.xkcd-webserver  enabled  active   -
    ~$ snap remove xkcd-webserver
    xkcd-webserver removed
    ~$ snap install --skip-service-start xkcd-webserver
    xkcd-webserver 16.04-6 from Canonical✓ installed
    ~$ snap services xkcd-webserver
    Service                        Startup  Current   Notes
    xkcd-webserver.xkcd-webserver  enabled  inactive  -

WDYT?