cmd/libsnap-confine-private: explicit pointer arithmentic
Clang is more picky:

clang -DHAVE_CONFIG_H -I.    -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wno-unused-parameter -Werror  -g -O2 -MT libsnap-confine-private/a-snap-dir.o -MD -MP -MF libsnap-confine-private/.deps/a-snap-dir.Tpo -c -o libsnap-confine-private/a-snap-dir.o `test -f 'libsnap-confine-private/snap-dir.c' || echo './'`libsnap-confine-private/snap-dir.c
libsnap-confine-private/snap-dir.c:91:61: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
   91 |                 strncmp(target, SC_ALTERNATE_SNAP_MOUNT_DIR + 1, n) != 0) {
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
libsnap-confine-private/snap-dir.c:91:61: note: use array indexing to silence this warning
   91 |                 strncmp(target, SC_ALTERNATE_SNAP_MOUNT_DIR + 1, n) != 0) {
      |                                                             ^
      |                                 &                           [  ]
1 error generated.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>