interfaces,cmd: disallow O_NOTIFICATION_PIPE (#15418)
Linux 5.8 has added yet another method of obtaining events from the
kernel. This time, in the form of a flag to the pipe2 system call.
An LWN.net article [1] goes into all the details and is recommended
reading.

Mozilla has similarly discovered this and patched it [2] in the Firefox
sandbox.

The snap-seccomp entry uses O_EXCL as O_NOTIFICATION_PIPE as including
the actual header <linux/watch_queue.h> causes type definition errors.
```
In file included from /usr/include/asm/fcntl.h:1,
                 from /usr/include/linux/fcntl.h:5,
                 from /usr/include/linux/watch_queue.h:6,
                 from cmd/snap-seccomp/main.go:209:
/usr/include/asm-generic/fcntl.h:157:1: error: redefinition of struct or union 'struct f_owner_ex'
  157 | };
      | ^
In file included from /usr/include/bits/fcntl.h:61,
                 from /usr/include/fcntl.h:35,
                 from /usr/include/xfs/linux.h:29,
                 from /usr/include/xfs/xfs.h:9,
                 from /usr/include/xfs/xqm.h:9,
                 from cmd/snap-seccomp/main.go:56:
/usr/include/bits/fcntl-linux.h:276:8: note: originally defined here
  276 | struct f_owner_ex
      |        ^~~~~~~~~~
/usr/include/asm-generic/fcntl.h:217:1: error: redefinition of struct or union 'struct flock64'
  217 | };
      | ^
/usr/include/bits/fcntl.h:50:8: note: originally defined here
   50 | struct flock64
      |        ^~~~~~~
FAIL	github.com/snapcore/snapd/cmd/snap-seccomp [build failed]
```

[1] https://lwn.net/Articles/760714/
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1808320

Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34990

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
Co-authored-by: Maciej Borzecki <maciek.borzecki@gmail.com>