tests/main/high-user-handling: force kill test user's session (#13805)
* tests/main/high-user-handling: force kill test user's session

Apparently some test user processes may still be running when we try to remove
it.

2024-04-09 12:47:47 Restoring google-central:fedora-38-64:tests/main/high-user-handling (apr091230-325924)...
Error: 2024-04-09 12:47:47 Error restoring google-central:fedora-38-64:tests/main/high-user-handling (apr091230-325924) :
-----
+ tests.session -u hightest restore
umount: /run/user/4294967294/gvfs: no mount point specified.
umount: /run/user/4294967294/doc: no mount point specified.
+ userdel -r hightest
userdel: user hightest is currently used by process 39295
-----
.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

* tests/main/high-user-handling: fix description and summary

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

---------

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>