tests/regression/lp-1867193, lp-1867752: drop tests
The tests no longer work, but are also less relevant since we have a
test for lp-1844496.

-----
+ lxc exec bionic -- snap install maas --channel=2.7/edge
error: cannot perform the following tasks:
- Ensure prerequisites for "maas" are available (cannot install snap
base "core18": snap "core18" assumes unsupported features:
snapd2.61 (try to refresh snapd))

The tests were broken since switching to snapd snap in tests, since the
test essentially executed with snap deb from the archive:

garden:ubuntu-18.04-64 .../tests/regression/lp-1867193# lxc exec -t bionic -- snap version
snap    2.58+18.04.1
snapd   2.58+18.04.1
series  16
ubuntu  18.04
kernel  4.15.0-212-generic

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>